plugins {
    id 'application'
}

group = 'gg.vape.service'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'io.netty:netty-all:4.1.118.Final'

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'gg.vape.service.VapeServiceApplication'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

tasks.named('test') {
    useJUnitPlatform()
}
